# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 04:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='BOM名称')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOM单',
                'verbose_name_plural': 'BOM单',
            },
        ),
        migrations.CreateModel(
            name='BomList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, verbose_name='数量')),
                ('remark', models.CharField(blank=True, max_length=250, null=True, verbose_name='备注')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Bom')),
            ],
            options={
                'verbose_name': 'BOM列表',
                'verbose_name_plural': 'BOM列表',
            },
        ),
        migrations.CreateModel(
            name='BomTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, verbose_name='数量')),
                ('remark', models.CharField(blank=True, max_length=250, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '临时BOM表',
                'verbose_name_plural': '临时BOM表',
            },
        ),
        migrations.CreateModel(
            name='InOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(1, 'IN'), (0, 'OUT')], default=1, max_length=2)),
                ('bom', models.CharField(blank=True, max_length=50, null=True, verbose_name='BOM号码')),
            ],
            options={
                'verbose_name': '进出明细',
                'verbose_name_plural': '进出明细',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=200, verbose_name='编码')),
                ('modelname', models.CharField(blank=True, max_length=200, null=True, verbose_name='型号')),
                ('potting', models.CharField(blank=True, max_length=100, null=True, verbose_name='封装')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='位号')),
                ('qty', models.IntegerField(default=0, verbose_name='数量')),
                ('price', models.FloatField(default=0.0, verbose_name='单价')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('markup', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
            },
        ),
        migrations.AddField(
            model_name='inout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='inout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bomtemp',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='bomtemp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bomlist',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
    ]
