# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20160728_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ItemType',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='itemtype',
        ),
    ]
