# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20160728_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomtemp',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bomtemp',
            name='user',
        ),
        migrations.DeleteModel(
            name='BomTemp',
        ),
    ]
