# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20160801_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名称'),
        ),
    ]
