# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0005_auto_20160825_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='地区')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('code', models.CharField(max_length=20, verbose_name='编码')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='办公室')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.City')),
            ],
            options={
                'verbose_name': '办公室',
                'verbose_name_plural': '办公室',
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_perm', models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否有操作权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '是否操作权限',
                'verbose_name_plural': '是否操作权限',
            },
        ),
        migrations.CreateModel(
            name='UserCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.City')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户地区权限',
                'verbose_name_plural': '用户地区权限',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='buy_time',
            field=models.DateField(blank=True, null=True, verbose_name='购买时间'),
        ),
        migrations.AddField(
            model_name='item',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='item',
            name='on_user',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='item',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='item',
            name='use_date',
            field=models.DateField(blank=True, null=True, verbose_name='领用时间'),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='code',
            field=models.CharField(default=1, max_length=20, verbose_name='编码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Office'),
        ),
    ]
