# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20170119_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '固定资产', 'verbose_name_plural': '固定资产'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='markup',
        ),
        migrations.RemoveField(
            model_name='item',
            name='position',
        ),
        migrations.RemoveField(
            model_name='item',
            name='potting',
        ),
    ]
